
# Datenbank-Konfiguration (über Umgebungsvariablen abrufbar)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jodel2}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:test}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA-Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Test-Datenbank deaktivieren
spring.test.database.replace=none

# Security und OAuth2 Einstellungen
spring.security.enabled=false
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/my-realm

# Server Konfiguration
server.port=${SERVER_PORT:8080}
server.address=${SERVER_ADDRESS:0.0.0.0}
server.servlet.context-path=/

# Nach erfolgreicher Anmeldung zu deinem Frontend weiterleiten
spring.security.oauth2.client.registration.keycloak.redirect-uri=${FRONTEND_URL:http://localhost:3000/}